version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10

jobs:
  deploy:
    executor: node
    steps:
      - checkout
      - run: yarn install
      - run: |
          mkdir -p ~/.ssh
          echo 'github.com ssh-rsa github-key 
          ' >> ~/.ssh/known_hosts
      - run: yarn bolt publish

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
